### PR TITLE
[FEATURE] Add sage as a means for identification in DDA

### PR DESCRIPTION
**Pull request by jpfeuffer**
## PR checklist

This will be merged with dev container references for now and must be adapted to a release before the release of this pipeline. Only affects SageAdapter and IDPEP if enabled.

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@ypriverol if you want you can help with the documentation or start testing with this PR.

**Comment by ypriverol** [comment]
@jpfeuffer can we enable, one of the test to run sage with comet. ?

**Comment by jpfeuffer** [comment]
Yes. Probably just the openms version in consensusid.
But note that you will lose all the speed advantage of sage when using with other search engines.

**Comment by ypriverol** [comment]
@jpfeuffer in some cases we will run it alone but also I see the point in multi-search as a replacement of msgf+ which is really slow. After you fix the consesusID problem I will merge and test with a real dataset here.

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
