### PR TITLE
Update of quantms dev in nf-core

### PR DESCRIPTION
**Pull request by ypriverol**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
    - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [x] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ypriverol** [comment]
@jpfeuffer can this PR be deleted. ?

**Review by jpfeuffer — APPROVED** [review]
Since all the PRs were reviewed separately, I approve if tests pass.

**Review by daichengxin — APPROVED** [review]

**Comment by ypriverol** [comment]
@ewels One of the tests linting is not passing. This is related with the issue we discussed in the morning about  is related with the issue we `files_unchangedassets/multiqc_config.yaml` not matching the template. What do we do in those cases?

**Comment by jpfeuffer** [comment]
I think you can merge this one when all tests except linting pass. We need to create a cleaner PR for the release without all the template changes anyway.
I think you can add a lint ignore for that linting errorml until it is fixed.

**Comment by ypriverol** [comment]
> I think you can merge this one when all tests except linting pass. We need to create a cleaner PR for the release without all the template changes anyway. I think you can add a lint ignore for that linting errorml until it is fixed.

where i can do the lint ignore. The lint test looks like required, don't know if we can force merge @jpfeuffer

**Comment by jpfeuffer** [comment]
.nf-core.yaml I think.
Where you removed all the lint ignore steps :D

**Comment by jpfeuffer** [comment]
It's not called lint-ignore but lint. Might be a worthwhile change on nf-core side ;)

**Comment by ypriverol** [comment]
> .nf-core.yaml I think. Where you removed all the lint ignore steps :D

.nf-core.yaml is one line 

```
repository_type: pipeline
```
The opther linting validation was different was in the yaml files.

**Comment by jpfeuffer** [comment]
Yes because you removed the rest

**Comment by jpfeuffer** [comment]
@ewels There seems to be a "run workflow tests" that is expected but not triggered. Sth in the GH settings?

**Comment by ypriverol** [comment]
@jpfeuffer @ewels do you have an idea what is going on here now?

**Pull request merged**
